/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [
    // Grid and layout
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'xl:grid-cols-4',
    'gap-6',
    'auto-rows-max',
    'max-w-7xl',
    'mx-auto',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'py-12',

    // Colors
    'bg-white',
    'bg-gradient-to-r',
    'from-[#002C56]',
    'to-[#0a4a8f]',
    'from-gray-200',
    'to-gray-300',
    'bg-gray-200',
    'text-white',
    'text-[#002C56]',
    'text-gray-900',
    'text-gray-700',
    'text-gray-100',
    'text-gray-400',
    'text-gray-600',
    'bg-[#002C56]',
    'bg-[#cfdbe9]',
    'bg-white/95',
    'bg-white/30',
    'bg-white/50',
    'bg-black/50',
    'bg-black/20',

    // Shadows and borders
    'shadow-sm',
    'shadow-xl',
    'border-b',
    'border-t',
    'border-gray-100',
    'border-gray-300',
    'rounded-lg',
    'rounded-full',
    'overflow-hidden',

    // Flexbox
    'flex',
    'flex-col',
    'flex-1',
    'flex-shrink-0',
    'items-center',
    'items-start',
    'justify-center',
    'justify-between',
    'justify-end',
    'gap-2',
    'gap-6',
    'h-full',

    // Animations
    'animate-pulse',
    'transition-all',
    'transition-transform',
    'transition-opacity',
    'duration-200',
    'duration-300',
    'duration-500',
    'scale-100',
    'scale-105',
    'opacity-0',
    'opacity-100',
    'drop-shadow-lg',
    'drop-shadow-md',
    'hover:shadow-xl',
    'hover:bg-[#001f3f]',
    'hover:bg-[#cfdbe9]',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-[#002C56]',
    'focus:border-transparent',

    // Spacing
    'p-2',
    'p-2.5',
    'p-3',
    'p-4',
    'py-2',
    'py-2.5',
    'py-3',
    'py-4',
    'py-12',
    'py-16',
    'px-2',
    'px-3',
    'px-4',
    'px-8',
    'pt-16',
    'm-4',
    'mt-3',
    'mb-4',
    'mb-8',
    'space-y-6',
    'space-y-1.5',

    // Sizing
    'w-full',
    'w-5',
    'w-20',
    'h-full',
    'h-64',
    'h-80',
    'h-96',
    'h-1',
    'h-5',
    'min-h-screen',
    'max-w-xl',
    'max-w-2xl',

    // Typography
    'text-xs',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'font-bold',
    'font-medium',
    'font-semibold',
    'leading-tight',
    'leading-snug',
    'line-clamp-1',
    'line-clamp-2',
    'truncate',

    // Utilities
    'sticky',
    'top-0',
    'top-20',
    'z-10',
    'z-40',
    'z-50',
    'cursor-pointer',
    'touch-manipulation',
    'pointer-events-none',
    'absolute',
    'inset-0',
    'left-0',
    'top-2',
    'left-2',
    'right-0',
    'bottom-0',
    '-mr-48',
    '-mt-48',
    '-ml-36',
    '-mb-36',
    '-translate-y-1/2',
    'hidden',
    'block',
    'inline-block',
    'inline-flex',
    'break-inside-avoid',
    'aspect-video',
    'sm:inline',
    'sm:h-80',
    'md:h-96',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: '#fef7ee',
          100: '#fdedd3',
          200: '#fad6a5',
          300: '#f6b96d',
          400: '#f19332',
          500: '#ed7411',
          600: '#de5907',
          700: '#b84309',
          800: '#92360f',
          900: '#772e10',
          950: '#41150a',
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Guidee 品牌色彩
        guidee: {
          primary: '#002C56',
          background: '#EAF28C',
          orange: '#ed7411',
          blue: '#0ea5e9',
          green: '#10b981',
          red: '#ef4444',
          gray: {
            50: '#f9fafb',
            100: '#f3f4f6',
            200: '#e5e7eb',
            300: '#d1d5db',
            400: '#9ca3af',
            500: '#6b7280',
            600: '#4b5563',
            700: '#374151',
            800: '#1f2937',
            900: '#111827',
          }
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans TC', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        "slide-up": {
          from: { transform: "translateY(100%)", opacity: 0 },
          to: { transform: "translateY(0)", opacity: 1 },
        },
        "slide-down": {
          from: { transform: "translateY(-100%)", opacity: 0 },
          to: { transform: "translateY(0)", opacity: 1 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
      },
      boxShadow: {
        'guidee': '0 4px 6px -1px rgba(237, 116, 17, 0.1), 0 2px 4px -1px rgba(237, 116, 17, 0.06)',
        'guidee-lg': '0 10px 15px -3px rgba(237, 116, 17, 0.1), 0 4px 6px -2px rgba(237, 116, 17, 0.05)',
      }
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
}